config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :movimentacoes, only: [:index, :new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movimentacoes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
    enum :tipo, {saida: 'saida', entrada: 'entrada'}

    belongs_to :usuario

    validates :data, comparison: { less_than_or_equal_to: proc { Date.current } }
    validates :descricao, presence: true
    validates :descricao, length: {maximum:150}
    validates :valor, presence: true
    validates :tipo, presence: true
    validate :valida_se_existe_saldo

    def self.saldo_atual
        self.entrada.sum(:valor) - self.saida.sum(:valor)
        #self.entrada.sum(:valor) - self.saida.sum(:valor)
    end

    def self.total_entrada
        self.entrada.sum(:valor)
    end

    def self.total_saida
        self.saida.sum(:valor)
    end

    private

    def valida_se_existe_saldo
        return unless usuario
        return if entrada?
        return if valor.to_f <= usuario.movimentacoes.saldo_atual
            errors.add :valor, 'não há saldo suficiente'
    end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :movimentacoes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movimentacoes_controller.rb
class MovimentacoesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_movimentacao, only: %i[ destroy ]

  # GET /movimentacoes or /movimentacoes.json
  def index
    @movimentacoes = collection.order(data: :desc, created_at: :desc)
    @saldo = collection.saldo_atual
    @receita = collection.total_entrada
    @saida = collection.total_saida
  end

  # GET /movimentacoes/new
  def new
    @movimentacao = collection.new
  end

    # POST /movimentacoes or /movimentacoes.json
  def create
    @movimentacao = collection.new(movimentacao_params)

    respond_to do |format|
      if @movimentacao.save
        format.html { redirect_to movimentacoes_url, notice: "A movimentação foi criada com sucesso!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimentacoes/1 or /movimentacoes/1.json
  # def update
  #   respond_to do |format|
  #     if @movimentacao.update(movimentacao_params)
  #       format.html { redirect_to movimentacao_url(@movimentacao), notice: "Movimentacao was successfully updated." }
  #       format.json { render :show, status: :ok, location: @movimentacao }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @movimentacao.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /movimentacoes/1 or /movimentacoes/1.json
  def destroy
    @movimentacao.destroy

    respond_to do |format|
      format.html { redirect_to movimentacoes_url, notice: "A movimentação foi removida com sucesso!" }
      format.json { head :no_content }
    end
  end

  private

    def collection 
      current_usuario.movimentacoes
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_movimentacao
      @movimentacao = collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movimentacao_params
      params.require(:movimentacao).permit(:data, :descricao, :valor, :tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg|
      content_tag(:p, "- #{msg}.")
    }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = "Ooops!"
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{ message }.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map { |msg|
        content_tag(:li, "#{msg}.")
      }.join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end

app/helpers/movimentacoes_helper.rb
module MovimentacoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meus gastos pessoais</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-300">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/movimentacoes/_form.html.erb
<%= form_with(model: movimentacao, class: "contents") do |form| %>
  <% if movimentacao.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(movimentacao.errors.count, "erro",plural: "erros") %> detectado(s)</h2>

      <ul>
        <% movimentacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="my-5">
    <%= form.label :tipo %>
    <%= form.select :tipo, [['Entrada', 'entrada'], ['Saída', 'saida']],{}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5">
    <%= form.label :data %>
    <%= form.date_field :data, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :valor %>
    <%= form.number_field :valor, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/movimentacoes/_movimentacao.html.erb
<div id="<%= dom_id movimentacao %>" 
    class="p-6 rounded-lg shadow-lg bg-white flex <%= movimentacao.saida? ? 'text-red-700' : 'text-green-700'%>">
  <span class="mr-2">
    <%=l movimentacao.data%>
  </span>
  <span class="mr-2 flex-grow">
    <%= movimentacao.descricao%>
  </span>
  <span>
    <%= number_to_currency movimentacao.valor%>
  </span>
  
</div>

app/views/movimentacoes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="grid grid-cols-5 gap-5 mb-5">
    <div class="p-6 rounded-lg shadow-lg bg-white">
      <p>Saldo Atual</p>
      <p class="text-2xl font-bold">
        <%= number_to_currency @saldo %>
      </p>
    </div>

    <div class="p-6 rounded-lg shadow-lg bg-red-500 text-white block">
      <p>Total de gasto</p>
      <p class="text-2xl font-bold text-white block">
        <%= number_to_currency @saida %>
      </p>
    </div>

    <div class="p-6 rounded-lg shadow-lg bg-green-500 text-white block">
      <p>Receita</p>
      <p class="text-2xl font-bold text-white block">
        <%= number_to_currency @receita %>
      </p>
    </div>

  <%= link_to new_movimentacao_path,
                class: "rounded-lg shadow-lg p-6 bg-blue-600 text-white block font-medium text-center" do %>
      <span>Nova movimentação</span>
    <% end %>

    <%= link_to destroy_usuario_session_path,
                method: :delete,
                class: "rounded-lg shadow-lg p-6 bg-blue-600 text-white block font-medium text-center" do %>
      <span>Logado como <%= current_usuario.email %></span>
    <% end %>
  </div>

  <div id="movimentacoes" class="grid grid-cols-1 gap-4 min-w-full">
    <%= render @movimentacoes %>
  </div>
</div>

app/views/movimentacoes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova movimentação</h1>

  <%= render "form", movimentacao: @movimentacao %>

  <%= link_to 'Voltar para lista', movimentacoes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>